# Generated by Django 2.2.5 on 2019-09-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='reate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
